### PR TITLE
Fixed the timer

### LINKED ISSUE #88: Memory management and Slowdowns
**What do you want to change?**
After the dashboard runs for about 15-20 minutes the dashboard starts to slow down. Upon initial looking it seems that this is a memory management issue. Javascript is not known for its garbage collection but we should investigate deeper into why this is happening and what we can do to prevent it.

**Why make that change?**
In some cases we need to run the dash for a considerable amount of time. It is important to make sure we are always running at real-time for an _optimized workflow_ 
**Describe alternatives you've considered**
We are considering dumping data as soon as it is rendered into a file to prevent memory buildup. But more digging is necessary

**Additional context**

### LINKED ISSUE #97: Finalize Countdown Clocks
**What do you want to change?**
Having a countdown clock on the dashboard would be a intuitive way to visualize various timers on the embedded side of things.

**Why make that change?**
There are time we were sitting watching our watches when this would be more useful.

**Describe alternatives you've considered**
I mean Ryan's pretty good at counting perfect seconds....

**Additional context**

### PR DESCRIPTION
**Pull request by ezraboley**
# Description

- Please include a summary of the change and which issue (if applicable) is fixed
I re-wrote the Timer class to be a lot simpler and have a cleaner interface. It also no-longer uses an internal time, it will instead generate the time on-demand. I clocked it against a timer on my phone for 2 minutes and found no noticeable difference in the duration listed. 
- Resolves #97 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (readme)
- [x] My changes generate no new warnings or errors
- [ ] I have added tests/examples that prove my fix is effective or that my feature works
- [x] New and existing lint guidelines/tests/examples pass with my changes (run npm test locally)

### CODE REVIEW

**Comment by EUdds** [comment]
image

You can see in this chart that there is still an increasing saw tooth trend on our memory usage. So I'm going to say that this closes #97 but until we figure out what's causing that increasing memory usage, I want to leave #88 open

**Comment by EUdds** [comment]
With that being said, this is a lot better and I am not experiencing slowdowns either. I just want to make sure we're not pushing it further back.

**Comment by ezraboley** [comment]
> image
> 
> You can see in this chart that there is still an increasing saw tooth trend on our memory usage. So I'm going to say that this closes #97 but until we figure out what's causing that increasing memory usage, I want to leave #88 open

I'm not entirely sure still why it's steadily increasing, but I think the sawtooth is normalish since you're just seeing garbage collection periodically (hence drop down in heap usage). Could be if the autosave is being updated through a read/update/write pattern?

**Comment by EUdds** [comment]
I ran a half hour long memory test and turns out that memory does stabilize and this seems to fix our memory issues 
image. I will close that issue

**Pull request merged**
